### ISSUE TITLE
Does AST matching relies on plausible patches or independent?

### ISSUE THREAD

**Issue by BEbillionaireUSD** [ASSERT-KTH/repairbench#5]
In the result directory, if only`ast_match` is available, does it mean no plausible patches are generated? Or the AST matching is only triggered upon plausible patches?

**Comment by andre15silva** [comment]
All `ast_match` patches are also plausible, and the `ast_match` script is only run on patches that pass all the tests previously.

**Comment by BEbillionaireUSD** [comment]
Thanks for you reply!
